# Generated by Django 3.2.10 on 2022-01-25 16:10

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('anulate', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('payment_type', models.CharField(choices=[('0', 'CARD'), ('1', 'TRANSFER'), ('2', 'UPON DELIVERY')], max_length=2)),
                ('invoice_type', models.CharField(choices=[('0', 'TICKET'), ('1', 'INVOICE'), ('2', 'OTHER')], max_length=2)),
                ('state', models.CharField(blank=True, choices=[('0', 'In process'), ('1', 'Sent'), ('2', 'In store'), ('3', 'Delivered')], max_length=2, null=True)),
                ('canceled', models.BooleanField(default=False)),
                ('address', models.TextField()),
                ('anulated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
