# Generated by Django 3.2.10 on 2022-01-26 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_rename_anulate_detail_anulated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='anulated',
            new_name='canceled',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='anulated',
        ),
    ]
