# Generated by Django 3.2.10 on 2022-01-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20220126_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='state',
            field=models.CharField(choices=[('0', 'In process'), ('1', 'Sent'), ('2', 'In store'), ('3', 'Delivered')], default='0', max_length=2),
        ),
    ]
