# Generated by Django 3.2.10 on 2022-02-02 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220126_1945'),
        ('sale', '0005_alter_sale_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.color'),
        ),
    ]
